version: "3.4"

services:
  web:
    image: sasho1320/plant-shop
    build: ./plant_shop/
    command: gunicorn plant_shop.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./static:/tmp/plant_shop/static
      - ./media:/home/app/web/media
    ports:
      - 8000:8000
    env_file:
      - ./plant_shop/envs/.env
    depends_on:
      - postgres
  postgres:
    image: postgres
    platform: linux/amd64
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 
      POSTGRES_USER:
      POSTGRES_DB: plant_shop_db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql:/var/lib/postgresql/data
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./static:/home/app/web/static
      - ./media:/home/app/web/media
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - web
